build-job:
  stage: build
  script:
    - echo "build job placeholder"


test-job-API:
  stage: test
  image: node:14
  script:
    - cd MathGamesAPI
    - npm i npm@latest -g
    - npm i
    - npm test

test-job-WebApp:
  stage: test
  image: node:14
  script:
    - cd WebApp/mathgames_app
    - yarn install
    - yarn build

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
