build-job-WebApp:
  stage: build
  image: node:14
  script:
    - cd WebApp/mathgames_app
    - yarn install
    - yarn build

test-job-API:
  stage: test
  image: node:14
  script:
    - cd MathGamesAPI
    - npm i npm@latest -g
    - npm i
    - npm test