build-job:
  stage: build
  script:
    - echo "build job placeholder"


test-job1:
  stage: test
  image: node:14
  script:
    - cd MathGamesAPI
    - npm i npm@latest -g
    - npm i
    - npm run build

test-job2:
  stage: test
  image: node:14
  script:
    - cd WebApp/mathgames_app
    - npm i npm@latest -g
    - npm i
    - npm run build

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
