/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Alex_F (https://sketchfab.com/Alex_F)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/53dd57e2352f45128f26e41eadd36699
title: Pixel Art/Voxel Art (Deal With It Glasses)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PixelGlasses(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + 'avatar_assets/accessories/pixelGlasses.glb')

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI/2, Math.PI, 0 ]}>
        <group position={[-0.6, -0.4, 1.4]} scale={[0.035, 0.05, 0.05]}>
          <mesh geometry={nodes.mesh_0.geometry} material={materials.material} />
          <mesh geometry={nodes.mesh_1.geometry} material={materials.JoinedMaterial_2} />
          <mesh geometry={nodes.mesh_2.geometry} material={materials.JoinedMaterial_4} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/PixelGlasses.glb')
