/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Kisielev Mikhail (https://sketchfab.com/kiselevmiki)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/steampunk-glasses-808866ce78a24354ae871c0f8721097f
title: steampunk glasses
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + 'avatar_assets/accessories/steamPunkGlasses.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={[0.01, 0.008, 0.006]} position={[0, 1.6, 0.6]}> 
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.LOW_2_NewMat01_0.geometry} material={materials.NewMat01} />
          <mesh geometry={nodes.LOW_3_Default_0.geometry} material={materials.Default} />
          <mesh geometry={nodes.LOW1_wire_028149177_0.geometry} material={materials.wire_028149177} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/steamPunkGlasses.glb')
