/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: shedmon (https://sketchfab.com/shedmon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/christmas-hat-b44d66b16ba543c9825af6f95bd3d678
title: Christmas Hat
*/

import { React, useRef } from "react";
import { useGLTF } from "@react-three/drei";

function ChristmasHat(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + 'avatar_assets/hats/christmasHat.glb')

  return (
    <group ref={group} {...props} dispose={null} scale={[0.08,0.08,0.08]} position={[0.3, 2.3, 0.1]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 0]} rotation={[0.37, -0.04, -0.11]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.mesh_0.geometry} material={materials.material} />
        </group>
      </group>
    </group>
  )
}

// useGLTF.preload('/christmasHat.glb')
export default ChristmasHat;
