/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: GSXNet (https://sketchfab.com/gsxn)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/models/e8d5a5d300024a7fa981cd294e97ce60
title: Sombrero hat 3D scan
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + 'avatar_assets/hats/cowboyHat.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={[6, 5, 5  ]} position={[-0.03, 2.12 , -0.09]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Material_001-material'].geometry} material={materials.Material_001} />
      </group>
    </group>
  )
}

useGLTF.preload('/cowboyHat.glb')
