/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: JalenJacobson (https://sketchfab.com/JalenJacobson)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/police-hat-3ccb6b620ee34fc0a1c1b403d11eca9b
title: Police Hat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + 'avatar_assets/hats/policeHat.glb')
  return (
    <group ref={group} {...props} dispose={null} position={[0, 1.73, 0.2]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 1]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.lambert4SG} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.lambert7SG} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.mesh_4.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.mesh_5.geometry} material={materials.lambert8SG} />
        <mesh geometry={nodes.mesh_6.geometry} material={materials.lambert2SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/policeHat.glb')