/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Eques_inferno (https://sketchfab.com/Eques_inferno)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/witch-hat-444a0c2f7ed449be9f127341b4eb2137
title: Witch Hat
*/

import { React, useRef } from "react";
import { useGLTF } from "@react-three/drei";


function WitchHat(props) {
	const group = useRef();
	const { nodes } = useGLTF(process.env.PUBLIC_URL + 'avatar_assets/hats/witchHat.glb')
  
	return (
		<group ref={group} {...props} dispose={null} scale={[0.5,0.5,0.5]} position={[0, 1.75, 0]}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group position={[0, 0.17, -0.29]} rotation={[0.18, 0, 0]}>
						<mesh geometry={nodes.eye1_low_HAT_0.geometry} material={nodes.eye1_low_HAT_0.material} />
					</group>
					<group position={[0.25, 0.31, 0.37]} rotation={[0.12, -0.8, 0.56]} scale={[0.87, 0.87, 0.87]}>
						<mesh geometry={nodes.eye2_low_HAT_0.geometry} material={nodes.eye2_low_HAT_0.material} />
					</group>
						<mesh geometry={nodes.Hatbase_low_HAT_0.geometry} material={nodes.Hatbase_low_HAT_0.material} />
						<mesh geometry={nodes.scraft_low_HAT_0.geometry} material={nodes.scraft_low_HAT_0.material} />
					<group position={[-0.16, 0.61, -3.72]} rotation={[-1.81, 0.1, -0.13]} scale={[0.04, 0.06, 0.04]}>
						<mesh geometry={nodes.H6_low_HAT_0.geometry} material={nodes.H6_low_HAT_0.material} />
					</group>
					<group position={[-0.17, 0.34, -3.72]} rotation={[-2.05, 0.18, -0.13]} scale={[0.05, 0.07, 0.05]}>
						<mesh geometry={nodes.H5_low_HAT_0.geometry} material={nodes.H5_low_HAT_0.material} />
					</group>
					<group position={[-0.06, 0.45, -3.46]} rotation={[-0.11, 0.73, -2.24]} scale={[0.03, 0.04, 0.03]}>
						<mesh geometry={nodes.H4_low_HAT_0.geometry} material={nodes.H4_low_HAT_0.material} />
					</group>
					<group position={[-0.37, 0.45, -3.44]} rotation={[-0.12, -0.67, 2.47]} scale={[0.03, 0.04, 0.03]}>
						<mesh geometry={nodes.H3_low_HAT_0.geometry} material={nodes.H3_low_HAT_0.material} />
					</group>
					<group position={[-0.17, 0.24, -3.78]} rotation={[-2.31, -0.03, -0.33]} scale={[0.02, 0.04, 0.02]}>
						<mesh geometry={nodes.H2_low_HAT_0.geometry} material={nodes.H2_low_HAT_0.material} />
					</group>
					<group position={[-0.3, 0.71, -3.58]} rotation={[-1.2, -0.73, 0.47]} scale={[0.02, 0.03, 0.02]}>
						<mesh geometry={nodes.H1_low_HAT_0.geometry} material={nodes.H1_low_HAT_0.material} />
					</group>
				</group>
			</group>
		</group>
	)
}
export default WitchHat;
